### ISSUE TITLE
:name option passed to Client.new is ignored

### ISSUE THREAD

**Issue by KOBA789** [cookpad/garage_client#19]
Run this code
```ruby
client = GarageClient::Client.new(name: 'awesome-name', endpoint: 'http://localhost')
client.get('/')
```
then raises:
```
RuntimeError: Configuration error: missing name
from <truncated>/gems/garage_client-2.3.3/lib/garage_client/configuration.rb:45:in `name'
```

Is this behavior intended?

**Comment by eagletmt** [comment]
Yes. My intention in #14 is enforcing application-wide name rather than client-local name because I think all requests from one application should have the same name.

I'll improve README.md to emphasize it.

**Comment by KOBA789** [comment]
I see. I was confused.
Thank you.
